'use strict';

module.exports = {
    extends: 'stylelint-config-recommended',
    plugins: ['stylelint-prettier'],
    rules: {
        'prettier/prettier': true,
        'color-named': 'never',
        'function-url-no-scheme-relative': true,
        'number-max-precision': 6,
        'unit-blacklist': ['em'],
        'shorthand-property-no-redundant-values': true,
        'value-no-vendor-prefix': true,
        'property-no-vendor-prefix': true,
        'declaration-block-no-redundant-longhand-properties': true,
        'declaration-no-important': true,
        'selector-attribute-operator-blacklist': '*=',
        'selector-combinator-blacklist': '>',
        'selector-max-attribute': 1,
        'selector-max-class': 2,
        'selector-max-combinators': 2,
        'selector-max-id': 0,
        'selector-max-pseudo-class': 1,
        'selector-max-type': 1,
        'selector-max-universal': 1,
        'selector-no-vendor-prefix': true,
        'selector-pseudo-element-whitelist': ['before', 'after', 'placeholder'], //CHECK first letter first line
        'media-feature-name-whitelist': 'min-width',
        'media-feature-name-no-vendor-prefix': true,
        'at-rule-blacklist': 'import',
        'at-rule-no-vendor-prefix': true,
        'no-unknown-animations': true,
        'color-hex-case': 'lower',
        'color-hex-length': 'short',
        'font-family-name-quotes': 'always-where-recommended',
        'font-weight-notation': 'numeric',
        'number-no-trailing-zeros': true,
        'string-quotes': 'single',
        'length-zero-no-unit': true,
        'unit-case': 'lower',
        'value-keyword-case': 'lower',
        'property-case': 'lower',
        'function-name-case': 'lower',
        'function-url-quotes': 'always',
        'declaration-empty-line-before': 'never',
        'declaration-block-trailing-semicolon': 'always',
        'selector-attribute-quotes': 'always',
        'selector-pseudo-class-case': 'lower',
        'selector-pseudo-element-case': 'lower',
        'selector-type-case': 'lower',
        'selector-pseudo-element-colon-notation': 'double',
        'rule-empty-line-before': 'always',
        'media-feature-name-case': 'lower',
        'media-feature-range-operator-space-after': 'always',
        'media-feature-range-operator-space-before': 'always',
        'comment-whitespace-inside': 'always',
        'max-empty-lines': 1,
        'no-eol-whitespace': true,
        'no-empty-first-line': true,
        // 'selector-no-qualifying-type': { ignore: ['class', 'id'] }, // TODO
        // 'custom-property-empty-line-before': NaN, // TODO
    },
};
