'use strict';

module.exports = {
    extends: 'stylelint-config-recommended',
    plugins: ['stylelint-prettier'],
    rules: {
        'prettier/prettier': true,
        'at-rule-empty-line-before': [
            'always',
            {
                except: ['blockless-after-same-name-blockless', 'first-nested'],
                ignore: ['after-comment'],
                ignoreAtRules: ['if', 'else'],
            },
        ],
        'unit-blacklist': ['em'],
        'at-rule-blacklist': 'import',
        'at-rule-no-vendor-prefix': true,
        'color-hex-case': 'lower',
        'color-hex-length': 'short',
        'color-named': 'never',
        'comment-empty-line-before': 'never',
        'comment-no-empty': true,
        'comment-whitespace-inside': 'always',
        'declaration-block-no-redundant-longhand-properties': true,
        'declaration-block-trailing-semicolon': 'always',
        'declaration-colon-space-after': 'always',
        'declaration-colon-space-before': 'never',
        'declaration-empty-line-before': 'never', // issue with comment
        'declaration-no-important': true,
        'font-family-name-quotes': 'always-where-recommended',
        'font-weight-notation': 'numeric',
        'function-name-case': 'lower',
        'function-url-no-scheme-relative': true,
        'function-url-quotes': 'always',
        'length-zero-no-unit': true,
        'max-empty-lines': 1,
        'media-feature-colon-space-after': 'always',
        'media-feature-colon-space-before': 'never',
        'media-feature-name-case': 'lower',
        'media-feature-name-no-vendor-prefix': true,
        'media-feature-name-whitelist': 'min-width',
        'media-feature-parentheses-space-inside': 'never',
        'media-feature-range-operator-space-after': 'always',
        'media-feature-range-operator-space-before': 'always',
        'no-duplicate-selectors': true,
        'no-empty-first-line': true,
        'no-eol-whitespace': true,
        'number-leading-zero': 'always',
        'number-max-precision': 6,
        'number-no-trailing-zeros': true,
        'property-case': 'lower',
        'property-no-vendor-prefix': true,
        'rule-empty-line-before': ['always', { except: ['first-nested'] }],
        'selector-attribute-brackets-space-inside': 'never',
        'selector-attribute-operator-blacklist': '*=',
        'selector-attribute-operator-space-after': 'never',
        'selector-attribute-operator-space-before': 'never',
        'selector-attribute-quotes': 'always',
        'selector-combinator-space-after': 'always',
        'selector-max-attribute': 1,
        'selector-max-class': 2,
        'selector-max-combinators': 2,
        'selector-max-id': 0,
        'selector-max-pseudo-class': 1,
        'selector-max-type': 1,
        'selector-max-universal': 1,
        'selector-no-qualifying-type': [true, { ignore: ['attribute'] }],
        'selector-no-vendor-prefix': true,
        'selector-pseudo-class-case': 'lower',
        'selector-pseudo-class-parentheses-space-inside': 'never',
        'selector-pseudo-element-case': 'lower',
        'selector-pseudo-element-colon-notation': 'double',
        'selector-type-case': 'lower',
        'shorthand-property-no-redundant-values': true,
        'string-quotes': 'single',
        'unit-case': 'lower',
        'value-keyword-case': 'lower',
        'value-no-vendor-prefix': true,
    },
};
